"""
review_comment.py — The ReviewComment table.

Represents a single inline comment generated by the AI analysis.
Each comment is tied to an AnalysisJob and targets a specific file
and line number in the PR diff.

The `github_comment_id` is nullable because:
  1. Comments are created locally first (from LLM response)
  2. Then posted to GitHub via API
  3. GitHub returns its own ID, which we store for deduplication
  If posting fails, we still have the comment locally.
"""

import uuid

from sqlalchemy import BigInteger, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.base import TimestampMixin


class ReviewComment(Base, TimestampMixin):
    __tablename__ = "review_comments"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    file_path: Mapped[str] = mapped_column(String(500), nullable=False)
    line_number: Mapped[int] = mapped_column(Integer, nullable=False)
    comment_body: Mapped[str] = mapped_column(Text, nullable=False)
    # Severity levels: info, warning, error, critical
    severity: Mapped[str] = mapped_column(
        String(20), default="info", nullable=False
    )
    # Set after successfully posting to GitHub — nullable until posted
    github_comment_id: Mapped[int | None] = mapped_column(
        BigInteger, nullable=True
    )

    # FK to the analysis job that produced this comment
    analysis_job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("analysis_jobs.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )

    # ── Relationships ────────────────────────────────────────────────────────
    analysis_job: Mapped["AnalysisJob"] = relationship(  # noqa: F821
        back_populates="comments",
    )

    def __repr__(self) -> str:
        return f"<ReviewComment id={self.id} {self.file_path}:{self.line_number} [{self.severity}]>"
